[package]
name = "mth_editor"
version.workspace = true
edition.workspace = true

[dependencies]
mth_common = { path = "../../crates/mth_common" }
mth_parser = { path = "../../crates/mth_parser" }
code_generator = { path = "../../crates/code_generator" }
graph_canvas = { path = "../../crates/graph_canvas" }

glam = { version = "0.31.0", features = ["bytemuck"] }
iced = { version = "0.14.0", features = ["canvas", "highlighter", "advanced"] }
